[build]
builder = "DOCKERFILE"
dockerfilePath = "SWR302-fe-homelanding/AppointmentApi/Dockerfile"
buildDirectory = "SWR302-fe-homelanding/AppointmentApi"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://+:8080" 