[build]
builder = "DOCKERFILE"
dockerfilePath = "SWR302-fe-homelanding/AppointmentApi/Dockerfile"
# Không cần buildDirectory vì đã chỉ định đường dẫn đầy đủ đến Dockerfile

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080" 