[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
# Không sử dụng buildDirectory để Railway tìm Dockerfile trong thư mục gốc

[deploy]
# Tạm thời tắt healthcheck để kiểm tra xem ứng dụng có khởi động được không
# healthcheckPath = "/health"
# healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8080" 